# Generated by Django 3.2 on 2021-04-11 07:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('geofence', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'factories',
            },
        ),
        migrations.CreateModel(
            name='FactoryUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.factory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factory_users',
            },
        ),
    ]
