# Generated by Django 3.2 on 2021-04-20 03:08

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.utils.timezone import utc
from django.contrib.gis.geos import Polygon


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="external_geofence",
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=Polygon(((0, 0), (0, 1), (1, 1), (0, 0))), srid=4326
            ),
            preserve_default=False,
        ),
    ]
