# Generated by Django 3.2 on 2021-05-01 04:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_factory_external_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='external_geofence',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
